admin_album:
    pattern:  /
    defaults: { _controller: "HellspiteMediaBundle:Album:index" }

admin_album_show:
    pattern:  /{id}/show
    defaults: { _controller: "HellspiteMediaBundle:Album:show" }

admin_album_new:
    pattern:  /new
    defaults: { _controller: "HellspiteMediaBundle:Album:new" }

admin_album_create:
    pattern:  /create
    defaults: { _controller: "HellspiteMediaBundle:Album:create" }
    requirements: { _method: post }

admin_album_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HellspiteMediaBundle:Album:edit" }

admin_album_update:
    pattern:  /{id}/update
    defaults: { _controller: "HellspiteMediaBundle:Album:update" }
    requirements: { _method: post }

admin_album_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HellspiteMediaBundle:Album:delete" }
    requirements: { _method: post }
