parameters:
#    hellspite_main.example.class: Hellspite\MainBundle\Example

services:
#    hellspite_main.example:
#        class: %hellspite_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
