parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     hellspite
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       smtp.servergrove.com
    mailer_user:       hellspite@hellspite.com
    mailer_password:   hellmail89

    locale:            en
    secret:            966103b374a03798f5838f8d7ffd1a461
