HellspiteTwitterBundle:
    resource: "@HellspiteTwitterBundle/Resources/config/routing.yml"
    prefix:   /

HellspiteAnnounceBundle_admin_post:
    resource: "@HellspiteAnnounceBundle/Resources/config/routing/post.yml"
    prefix:   /admin/post

HellspiteAnnounceBundle:
    resource: "@HellspiteAnnounceBundle/Resources/config/routing.yml"
    prefix:   /

HellspiteMainBundle:
    resource: "@HellspiteMainBundle/Resources/config/routing.yml"
    prefix:   /main

HellspiteTemporaryBundle:
    resource: "@HellspiteTemporaryBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
