HellspiteAnnounceBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: HellspiteAnnounceBundle:Default:index }

HellspiteAnnounceBundle_show:
    pattern:  /post/{slug}
    defaults: { _controller: HellspiteAnnounceBundle:Default:show }
