HellspiteAnnounceBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: HellspiteAnnounceBundle:Default:index }

HellspiteAnnounceBundle_show:
    pattern:  /{_locale}/post/{slug}
    defaults: { _controller: HellspiteAnnounceBundle:Default:show }
    requirements:
       _locale:  en|it
