parameters:
#    hellspite_announce.example.class: Hellspite\AnnounceBundle\Example

services:
#    hellspite_announce.example:
#        class: %hellspite_announce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
