<?php

namespace Hellspite\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getAll(){
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->orderBy('a.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
