<?php

namespace Hellspite\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function getByAlbum($album){
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.album = :album')
            ->setParameter('album', $album)
            ->getQuery();

        return $query->getResult();
    }
}
