<?php

namespace Hellspite\GigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GigRepository extends EntityRepository
{
    public function getNext(){
        $query = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.date >= :today')
            ->setParameter('today', date('Y-m-d'))
            ->orderBy('g.date', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function getPast(){
        $query = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.date <= :today')
            ->setParameter('today', date('Y-m-d'))
            ->orderBy('g.date', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
