<?php

namespace Hellspite\GigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GigRepository extends EntityRepository
{
}